version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "1111:1111"
    volumes:
      - ./:/app
      - /node_modules/
      - /.git/
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 1112
    ports:
      - "1112:1112"

